### ISSUE TITLE
blurry mintupdate checkmark

### ISSUE THREAD

**Issue by NikoKrause** [B00merang-Project/Windows-10-Icons#1]
The checkmark in mintupdate is blurry.
![screenshot-window-2017-04-08-131112](https://cloud.githubusercontent.com/assets/8415124/24828415/f0d2d564-1c5c-11e7-95db-6046daced69c.png)

If you give me a high resolution png of this checkmark, I can help you to improve it.

**Comment by feren** [comment]
@Elbullazul You may want to make a scalable version of that tick mark with Trace Bitmap, then scale it up, make it that green colour, and make an image out of it.

**Comment by cinnamoner** [comment]
@NikoKrause This issue was first signalled in the summer of 2016. My suggestion is to take the asset from KDE Neon. It's really good looking. I bet you won't be disappointed should Elbullazul choose to do so.

**Comment by Elbullazul** [comment]
@cinnamoner Neon doesn't use GTK-specific icons

@NikoKrause last time I tried to fix it cinnamon would not load the higher resolution asset.

I'll try again this week and post the results

**Comment by Elbullazul** [comment]
here's the result with SVG image:

![capture du 2017-04-08 21-46-33](https://cloud.githubusercontent.com/assets/15310985/24833916/f7cf3608-1ca4-11e7-8055-ef9d58672acf.png)

**Comment by Elbullazul** [comment]
pushed the fix

**Comment by NikoKrause** [comment]
Yeah. Do you want a green one?

**Comment by NikoKrause** [comment]
If you send me the SVG (and the green hex color code) I can help you.

**Comment by feren** [comment]
@NikoKrause My workaround to hooking the correct colour is to then save the hooked colour bit as an image, then reimport it into that SVG through Inkscape, and then it WILL keep its colour

**Comment by NikoKrause** [comment]
Yeah I did something similar. But I need the right checkmark. Tested it with another one

**Comment by Elbullazul** [comment]
@NikoKrause 256x256/actions/dialog-ok.png

**Comment by NikoKrause** [comment]
This is how it looks:
![screenshot-window-2017-04-08-131112](https://cloud.githubusercontent.com/assets/8415124/24851007/66ad1bfc-1dd2-11e7-856d-c029217e860f.png)

That's the file [object-select-symbolic.svg.zip](https://github.com/B00merang-Project/Windows-10-Icons/files/909312/object-select-symbolic.svg.zip)

I used this converter https://www.base64-image.de/
and pasted the code to `xlink:href=.......` in the svg file with a text editor.

**Comment by Elbullazul** [comment]
@nikokrause you put it in scalable/actions?

**Comment by NikoKrause** [comment]
Yes

**Comment by cinnamoner** [comment]
@NikoKrause Like it.
